rearranged

diff --git a/.devcontainer/Dockerfile b/.devcontainer/Dockerfile
--- a/.devcontainer/Dockerfile
+++ b/.devcontainer/Dockerfile
@@ -1,58 +1,56 @@
 ARG VARIANT=22-bookworm
 FROM mcr.microsoft.com/devcontainers/typescript-node:1-${VARIANT}
 
-# # [Option] Install zsh
-# ARG INSTALL_ZSH="true"
-# # [Option] Upgrade OS packages to their latest versions
-# ARG UPGRADE_PACKAGES="false"
-# # [Option] Enable non-root Docker access in container
-# ARG ENABLE_NONROOT_DOCKER="true"
-# # [Option] Use the OSS Moby Engine instead of the licensed Docker Engine
-# ARG USE_MOBY="true"
-# # [Optional] Uncomment this section to install additional OS packages.
-# # RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
-# #     && apt-get -y install --no-install-recommends <your-package-list-here># [Option] Engine/CLI Version
-# ARG DOCKER_VERSION="latest"
-
-# # Enable new "BUILDKIT" mode for Docker CLI
-# ENV DOCKER_BUILDKIT=1
-
-# # Install needed packages and setup non-root user. Use a separate RUN statement to add your
-# # own dependencies. A user of "automatic" attempts to reuse an user ID if one already exists.
-# ARG USERNAME=automatic
-# ARG USER_UID=1000
-# ARG USER_GID=$USER_UID
-# COPY library-scripts/*.sh /tmp/library-scripts/
-# RUN apt-get update \
-#     && /bin/bash /tmp/library-scripts/common-debian.sh "${INSTALL_ZSH}" "${USERNAME}" "${USER_UID}" "${USER_GID}" "${UPGRADE_PACKAGES}" "true" "true" \
-#     # Use Docker script from script library to set things up
-#     && /bin/bash /tmp/library-scripts/docker-in-docker-debian.sh "${ENABLE_NONROOT_DOCKER}" "${USERNAME}" "${USE_MOBY}" "${DOCKER_VERSION}" \
-#     # Clean up
-#     && apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/* /tmp/library-scripts/
-
-# VOLUME [ "/var/lib/docker" ]
-
-# # Setting the ENTRYPOINT to docker-init.sh will start up the Docker Engine 
-# # inside the container "overrideCommand": false is set in devcontainer.json. 
-# # The script will also execute CMD if you need to alter startup behaviors.
-# ENTRYPOINT [ "/usr/local/share/docker-init.sh" ]
-# CMD [ "sleep", "infinity" ]
-
-
-
 # Install GitHub CLI in case ssh-agent forwarding doesn't work (cough, cough, windows)
-# RUN (type -p wget >/dev/null || (sudo apt update && sudo apt-get install wget -y)) \
-#     && sudo mkdir -p -m 755 /etc/apt/keyrings \
-#     && wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
-#     && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
-#     && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
-#     && sudo apt update \
-#     && sudo apt install gh -y
+RUN (type -p wget >/dev/null || (sudo apt update && sudo apt-get install wget -y)) \
+    && sudo mkdir -p -m 755 /etc/apt/keyrings \
+    && wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
+    && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
+    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
+    && sudo apt update \
+    && sudo apt install gh -y
+
+# [Option] Install zsh
+ARG INSTALL_ZSH="true"
+# [Option] Upgrade OS packages to their latest versions
+ARG UPGRADE_PACKAGES="false"
+# [Option] Enable non-root Docker access in container
+ARG ENABLE_NONROOT_DOCKER="true"
+# [Option] Use the OSS Moby Engine instead of the licensed Docker Engine
+ARG USE_MOBY="true"
+# [Optional] Uncomment this section to install additional OS packages.
+# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
+#     && apt-get -y install --no-install-recommends <your-package-list-here># [Option] Engine/CLI Version
+ARG DOCKER_VERSION="latest"
+
+# Enable new "BUILDKIT" mode for Docker CLI
+ENV DOCKER_BUILDKIT=1
+
+# Install needed packages and setup non-root user. Use a separate RUN statement to add your
+# own dependencies. A user of "automatic" attempts to reuse an user ID if one already exists.
+ARG USERNAME=automatic
+ARG USER_UID=1000
+ARG USER_GID=$USER_UID
+COPY library-scripts/*.sh /tmp/library-scripts/
+RUN apt-get update \
+    && /bin/bash /tmp/library-scripts/common-debian.sh "${INSTALL_ZSH}" "${USERNAME}" "${USER_UID}" "${USER_GID}" "${UPGRADE_PACKAGES}" "true" "true" \
+    # Use Docker script from script library to set things up
+    && /bin/bash /tmp/library-scripts/docker-in-docker-debian.sh "${ENABLE_NONROOT_DOCKER}" "${USERNAME}" "${USE_MOBY}" "${DOCKER_VERSION}" \
+    # Clean up
+    && apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/* /tmp/library-scripts/
+
+VOLUME [ "/var/lib/docker" ]
+
+# Setting the ENTRYPOINT to docker-init.sh will start up the Docker Engine 
+# inside the container "overrideCommand": false is set in devcontainer.json. 
+# The script will also execute CMD if you need to alter startup behaviors.
+ENTRYPOINT [ "/usr/local/share/docker-init.sh" ]
+CMD [ "sleep", "infinity" ]
 
 # Install AWS CLI
-# RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
-#     && unzip awscliv2.zip \
-#     && sudo ./aws/install \
-#     && rm awscliv2.zip
+RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
+    && unzip awscliv2.zip \
+    && sudo ./aws/install \
+    && rm awscliv2.zip
 
-# RUN npm install -g aws-cdk
+RUN npm install -g aws-cdk
